// Generated by CoffeeScript 1.4.0
(function() {
  var debouncedSave, logDebug, saveText;

  logDebug = false;

  saveText = function() {
    return console.log("save text");
  };

  debouncedSave = _.debounce(saveText, 500);

  $(".container").keyup(debouncedSave);

}).call(this);
