// Generated by CoffeeScript 1.4.0
(function() {
  var $container, Page, PagesCollection, createDefaultPage, debouncedSave, logDebug, pageFetch, pages, postFetch, saveText, thePage;

  logDebug = false;

  $container = $(".container");

  Page = Backbone.Model.extend({
    defaults: {
      copy: ''
    }
  });

  PagesCollection = Backbone.Collection.extend({
    model: Page,
    url: '/api/pages.json'
  });

  pages = new PagesCollection();

  thePage = null;

  createDefaultPage = function() {
    if (logDebug) {
      console.log("len", pages.length);
    }
    if (pages.length > 0) {
      if (logDebug) {
        console.log("found page");
      }
      thePage = pages.at(0);
      return $container.html(thePage.get("copy"));
    } else {
      if (logDebug) {
        console.log("create page");
      }
      return thePage = pages.create({
        copy: $container.html()
      });
    }
  };

  postFetch = function() {
    return createDefaultPage();
  };

  saveText = function() {
    console.log("save text", thePage);
    thePage.set("copy", $container.html());
    return thePage.save();
  };

  debouncedSave = _.debounce(saveText, 100);

  $container.keyup(debouncedSave);

  pageFetch = pages.fetch();

  pageFetch.done(postFetch);

}).call(this);
